version: "3.8"
services:
  mysql:
    image: mysql
    #build: ./imagenes
    volumes:
      -  ./datos:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      - MYSQL_USER=${USER_}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql